services:
  - type: web
    name: crm-system
    env: docker
    region: ohio
    plan: free
    branch: main
    repo: https://github.com/amanladji/crm-project
    healthCheckPath: /api/customers
    envVars:
      - key: PORT
        value: 8080
